"""REST API for StudyGuard AI.

Thin transport: every route delegates to :class:`StudyGuardService`. No business
logic lives here. OpenAPI (Swagger at /docs, ReDoc at /redoc) is generated by
FastAPI. Versioned under /api/v1.
"""
from __future__ import annotations

from collections.abc import Callable
from functools import lru_cache

from fastapi import APIRouter, Depends, FastAPI, Query, Request
from fastapi.responses import JSONResponse

from studyguard import __version__
from studyguard.api import StudyGuardService
from studyguard.demo import build_demo_service
from studyguard.security import SECURITY_HEADERS
from studyguard.sources.consent import ConsentError
from studyguard.webapi.schemas import (
    CoachMessageModel,
    ConnectSourceRequest,
    GoalsModel,
)


@lru_cache
def _default_service() -> StudyGuardService:
    return build_demo_service()


def get_service() -> StudyGuardService:
    """Dependency provider (override in tests / production wiring)."""
    return _default_service()


def create_app(service_provider: Callable[[], StudyGuardService] = get_service) -> FastAPI:
    """Build the FastAPI app. ``service_provider`` is the DI seam."""
    app = FastAPI(
        title="StudyGuard AI API",
        version=__version__,
        description="Privacy-first study intelligence. Transport over StudyGuardService.",
        docs_url="/docs",
        redoc_url="/redoc",
    )
    app.state.request_count = 0

    from fastapi.middleware.cors import CORSMiddleware

    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.middleware("http")
    async def _count_requests(request: Request, call_next):
        app.state.request_count += 1
        response = await call_next(request)
        for header, value in SECURITY_HEADERS.items():
            response.headers.setdefault(header, value)
        return response

    @app.exception_handler(ConsentError)
    async def _consent_handler(_request: Request, exc: ConsentError) -> JSONResponse:
        return JSONResponse(status_code=403, content={"detail": str(exc)})

    @app.exception_handler(KeyError)
    async def _key_handler(_request: Request, exc: KeyError) -> JSONResponse:
        return JSONResponse(status_code=404, content={"detail": str(exc)})

    @app.exception_handler(ValueError)
    async def _value_handler(_request: Request, exc: ValueError) -> JSONResponse:
        return JSONResponse(status_code=400, content={"detail": str(exc)})

    dependency = Depends(service_provider)
    v1 = APIRouter(prefix="/api/v1", tags=["v1"])

    @app.get("/metrics", tags=["ops"])
    def metrics() -> dict:
        return {"requests": app.state.request_count, "version": __version__}

    @v1.get("/health", tags=["ops"])
    def health(service: StudyGuardService = dependency) -> dict:
        return service.get_health()

    @v1.get("/liveness", tags=["ops"])
    def liveness() -> dict:
        return {"status": "alive"}

    @v1.get("/readiness", tags=["ops"])
    def readiness(service: StudyGuardService = dependency) -> dict:
        storage = service.get_health().get("storage", {})
        return {"status": "ready", "storage": storage.get("status")}

    @v1.get("/sources")
    def list_sources(service: StudyGuardService = dependency) -> list[dict]:
        return service.list_sources()

    @v1.post("/consent/{key}")
    def grant_consent(key: str, service: StudyGuardService = dependency) -> dict:
        return service.grant_consent(key)

    @v1.delete("/consent/{key}")
    def revoke_consent(key: str, service: StudyGuardService = dependency) -> dict:
        return service.revoke_consent(key)

    @v1.post("/sources/{key}")
    def connect_source(
        key: str, body: ConnectSourceRequest, service: StudyGuardService = dependency
    ) -> dict:
        return service.connect_source(key, **body.config)

    @v1.delete("/sources/{key}")
    def disconnect_source(key: str, service: StudyGuardService = dependency) -> dict:
        return service.disconnect_source(key)

    @v1.get("/analytics")
    def analytics(service: StudyGuardService = dependency) -> dict:
        return service.get_analytics()

    @v1.get("/timeline")
    def timeline(
        service: StudyGuardService = dependency,
        limit: int = Query(default=100, ge=1, le=1000),
        offset: int = Query(default=0, ge=0),
        min_focus: float | None = Query(default=None, ge=0, le=100),
    ) -> list[dict]:
        rows = service.get_timeline()
        if min_focus is not None:
            rows = [row for row in rows if row.get("avg_focus", 0) >= min_focus]
        return rows[offset : offset + limit]

    @v1.get("/sessions")
    def sessions(
        service: StudyGuardService = dependency,
        limit: int = Query(default=100, ge=1, le=1000),
        offset: int = Query(default=0, ge=0),
    ) -> list[dict]:
        return service.get_sessions()[offset : offset + limit]

    @v1.get("/insights")
    def insights(service: StudyGuardService = dependency) -> dict:
        return service.get_insights()

    @v1.get("/recommendations")
    def recommendations(service: StudyGuardService = dependency) -> list[dict]:
        return service.get_recommendations()

    @v1.get("/coach", response_model=list[CoachMessageModel])
    def coach(service: StudyGuardService = dependency) -> list[dict]:
        return service.get_coach()

    @v1.get("/coach/weekly")
    def coach_weekly(service: StudyGuardService = dependency) -> dict:
        return service.get_weekly_summary()

    @v1.get("/goals", response_model=GoalsModel)
    def goals(service: StudyGuardService = dependency) -> dict:
        return service.get_goals()

    @v1.get("/hourly")
    def hourly(service: StudyGuardService = dependency) -> dict:
        return service.get_hourly()

    @v1.get("/planned-vs-actual")
    def planned_vs_actual(service: StudyGuardService = dependency) -> list[dict]:
        return service.get_planned_vs_actual()

    @v1.get("/reports")
    def reports(
        service: StudyGuardService = dependency,
        period: str = Query(default="week"),
        audience: str = Query(default="student"),
    ) -> dict:
        return service.get_report(period=period, audience=audience)

    @v1.get("/export/formats")
    def export_formats(service: StudyGuardService = dependency) -> list[str]:
        return service.export_formats()

    @v1.get("/export")
    def export(
        service: StudyGuardService = dependency,
        format: str = Query(default="json"),
        kind: str = Query(default="analytics"),
    ) -> dict:
        return service.export(format, kind=kind)

    @v1.get("/data/export")
    def data_export(service: StudyGuardService = dependency) -> list[dict]:
        return service.export_data()

    @v1.delete("/data")
    def data_delete(service: StudyGuardService = dependency) -> dict:
        return service.delete_data()

    app.include_router(v1)
    return app


app = create_app()


def run(host: str = "127.0.0.1", port: int = 8000) -> None:  # pragma: no cover - server entry
    """Console entry point: launch the API with uvicorn."""
    import uvicorn

    uvicorn.run(app, host=host, port=port)
